# Generated by Django 4.2.7 on 2023-12-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('datatime_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('project', models.BooleanField(default=True)),
                ('Productivity', models.CharField(choices=[('Great', 'Great'), ('Good', 'Good'), ('Bad', 'Bad')], max_length=50)),
                ('Certainty', models.CharField(choices=[('Confident', 'Confident'), ('Midst', 'Midst'), ('Vague', 'Vague')], max_length=50)),
                ('Health_Feeling', models.CharField(choices=[('Perfect', 'Perfect'), ('Normal', 'Normal'), ('Weakness', 'Weakness')], max_length=50)),
                ('Stage', models.CharField(choices=[('R&D', 'R&D'), ('Actin(Doing Task)', 'Actin(Doing Task)'), ('Cominucating', 'Cominucating'), ('Monitor', 'Monitor'), ('Setup Things', 'Setup Things')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='sheet',
        ),
    ]
