# Generated by Django 4.2.7 on 2023-12-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_post_delete_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='project',
        ),
    ]
