# Generated by Django 4.2.7 on 2023-12-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('productivity', models.CharField(choices=[('Great', 'great'), ('Good', 'good'), ('Bad', 'bad')], max_length=255)),
                ('certainty', models.CharField(choices=[('Confident', 'confident'), ('Midst', 'midst'), ('Vague', 'vague')], max_length=255)),
                ('health_feeling', models.CharField(choices=[('Perfect', 'perfect'), ('Normal', 'normal'), ('Weakness', 'weakness')], max_length=255)),
                ('stage', models.CharField(choices=[('R&D', 'r&d'), ('Action(Doing Task)', 'action_doing_task'), ('Cominucating', 'cominucating'), ('Monitor', 'monitor'), ('Setup Things', 'setup_things')], max_length=255)),
                ('project', models.CharField(choices=[('All', 'all'), ('Retail', 'retail'), ('Promotion', 'promotion'), ('IESCO', 'iesco'), ('DR hajitaghi Web', 'dR_hajitaghi_web'), ('Baraye Iran', 'baraye_iran'), ('Branding', 'branding'), ('DR hajitaghi App', 'dR_hajitaghi_app'), ('Setup things', 'setup_things')], max_length=255)),
            ],
        ),
    ]
